### ISSUE TITLE
Unable to change keyboard back light  

### ISSUE THREAD

**Issue by CodyRude** [mate-desktop/mate-power-manager#108]
I have an ASUS G73-jh laptop running Arch Linux. 

When I try to use the function keys to change my keyboard backlight, a notification for the backlight is displayed, but it doesn't change the actual keyboard backlight level.

I can use dbus to change the keyboard backlight using the dbus-send command.

I was able to get it mostly working by increasing the default step size in gpm-kbd-backlight.h via #define GPM_KBD_BACKLIGHT_STEP. I think the problem is that my keyboard backlight step sizes are 0, 33%, 66%, and 100%, and so the default 10% isn't large enough increase for it to change the value of my keyboard backlight.

After making the change the only problem is that it doesn't handle all possible step values. It will only go between 0%, 33%, and 66%. I can manually set it to 100% via dbus-send. The notification displayed when I increase the keyboard lights using the function keys show that the backlights are at 100% when its really at 66%.

**Comment by TriHexagon** [comment]
Same problem here (ASUS UX32).

**Comment by deflexor** [comment]
Same problem on ASUS N550 laptop

**Comment by monsta** [comment]
It seems to be fixed in https://github.com/mate-desktop/mate-power-manager/commit/8352686d856b164432732668afed24f248c17323.

**Comment by deflexor** [comment]
Does it fixed in 1.10.1 ? Because i have this version of MATE and it doesn't work.

**Comment by monsta** [comment]
No, we didn't release the next version yet where it's fixed.
