### ISSUE TITLE
Use UDisks2 in mate-power-manager

### ISSUE THREAD

**Issue by sunweaver** [mate-desktop/mate-power-manager#109]
Hi!

as udisks1 has been deprecated for a while now, I want to suggest making mate-power-manager udisks2-aware. I guess, for compatibility reasons, the udisks1 support should be kept for a while (there is no udisks2 in Debian wheezy).

See also: [1]

Greets,
Mike

[1] https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=750508

**Comment by sunweaver** [comment]
Phew... there has been no progress on this for MATE 1.10, as I see.

The udisks package is planned to be removed from Debian unstable within the next few weeks, see [1].

Any chance that udisks2 support gets added before mate-power-manager 1.10.x?

Mike

[1] https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=750508#23

**Comment by sunweaver** [comment]
meaning, the *udisks1* package is planned to be removed...

**Comment by monsta** [comment]
@sunweaver: fixed in https://github.com/mate-desktop/mate-power-manager/commit/405bec23c0a1cf97e39171fabc6596c9ab7f7a5e - you can close it.
