### ISSUE TITLE
more adjustments for 'critical actions' are needed for upower-0.99

### ISSUE THREAD

**Issue by raveit65** [mate-desktop/mate-power-manager#112]
In fedora-21 hibernate for 'critical actions' fails with upower-0.99.
Reason:
1. upower-0.99 calls now directly systemd for  'critical actions' when battery is low.
(old = upower --> m-p-m --> systemd)
2. default action for this is hybrid-sleep
see. https://wiki.archlinux.org/index.php/Power_management#Hybrid_sleep
So, we need to follow https://git.gnome.org/browse/gnome-settings-daemon/commit/plugins/power/gsd-power-manager.c?id=8e6a82c585fe16978f9e1ca3437a4b96dd4e6d34
and later commits.
Leigh from fedora cinnamon is preparing a patch for cinnamon-2.4.0 for fixing the issue.
I will see if that can be adopted for Mate.

**Comment by NiceandGently** [comment]
Now i have a downstream bug.
https://bugzilla.redhat.com/show_bug.cgi?id=1253937

**Comment by monsta** [comment]
@leigh123linux: which patch is mentioned here? Should we do the same as upstream (do nothing on critical events)?

**Comment by leigh123linux** [comment]
@monsta 

I never applied a fix for this as it worked without it on fedora.
