### ISSUE TITLE
mate-power-manager-bugreport doesn't work as it uses HAL

### ISSUE THREAD

**Issue by monsta** [mate-desktop/mate-power-manager#124]
Just look at its code.
HAL is obsolete and is removed from modern Debian and Ubuntu, for example.

**Comment by NiceandGently** [comment]
hal is a remnant from last century 😀 i don't think that a distro use it nowadays.

**Comment by monsta** [comment]
Fixed in https://github.com/mate-desktop/mate-power-manager/commit/c005217966cbe610fe25639dd9faa5a6e0a2cea2.
