### ISSUE TITLE
m-p-s crash when switching from battery tab "History" or "Statistics" back to AC Adapter

### ISSUE THREAD

**Issue by sunweaver** [mate-desktop/mate-power-manager#142]
works:

  AC Adapter [ Details ] tab
  Battery Adapter [ Details ] tab
  Battery Adapter [ HIstory ] or [ Statistics ] tab
  back to Battery Adapter [ Details ] tab
  back to AC Adapter [ Details ] tab

fails:

  AC Adapter [ Details ] tab
  Battery Adapter [ Details ] tab
  Battery Adapter [ HIstory ] or [ Statistics ] tab
  SKIP THIS: back to Battery Adapter [ Details ] tab
  back to AC Adapter [ Details ] tab

"""
[mike@minobo mate-power-manager.pkg]$ mate-power-statistics 
Segmentation fault
"""

Is it possible, that the UI tries to acces the previously used tab name / identifier on the AC Adapter?

This is in mate-power-manager 1.8.1-5 (currently preparing that upload for Debian).

Mike

**Comment by pudh4418** [comment]
I think this is a duplicate of issue #129

**Comment by monsta** [comment]
@sunweaver: I guess you can close it when upower 0.99.1-3.2 reaches Jessie...

**Comment by sunweaver** [comment]
Closing it now... @monsta: thanks for reminding me.
