### ISSUE TITLE
/usr/share/help/es/mate-power-manager/figures/gs-prefs.png

### ISSUE THREAD

**Issue by texstar** [mate-desktop/mate-power-manager#169]
A very minor report but it appears the /usr/share/help/es/mate-power-manager/figures/gs-prefs.png graphic image is corrupt.

**Comment by raveit65** [comment]
Thank you
https://github.com/mate-desktop/mate-power-manager/commit/7a2dd8f9f2bd4b9033d42e4428b87bd0385b0824
