### ISSUE TITLE
Can't control Brightness in Debian

### ISSUE THREAD

**Issue by MikeAlreadyTaken** [mate-desktop/mate-power-manager#181]
Hey everyone,

Firstly, i would like to admit that i am a total noob concerning linux. Secondly, i would like to tell that english is not my mother language. So, please, forgive me every stupid questions i could ask and every grammar mistakes i could do.

So, i buy a couple days ago a Dell  Inspiron 3552 Ubuntu. I tried Ubuntu, Mint and Debian. I tried Mate, XFDE, LXDE and Unity. I chose a Debian+MATE experience.
Debian is 8.3. MATE is 1.8.1.

Firstly, I was able to start Ubuntu and Mint in UEFI. But, I had to use Legacy for Debian. I don't know if it could be relevant or not. So, i just tell.

Secondly, I was able to change brightness with my hotkeys in both Ubuntu (Unity) and Mint (MATE). But, it actually doesn't work at all in Debian ... In fact, to be perfectly clear, in the "Power Management", there is no "set brightness to" in both in the "AC Power" and "Battery Power". Nothing, not even not working nor "grey over".
![screenshot](https://cloud.githubusercontent.com/assets/18178869/14161865/3b771180-f6e7-11e5-9e8a-7b8782ae6dc6.png)
Nevertheless, in "Battery Power", I can check and uncheck "reduce backlight brightness". But, it's not working at all.
In addition, I can add to my panel "Brightness Applet", I can turn it up or down by scrolling or cliking. But, guess what ? Not working.

Thirdly, I check that mate-power-manager was installed in synaptic and up to date. I run a  verbose. Everything turns to be green (what i suppose is a good thing ...) except :

```
TI:02:11:04	TH:0x1694270	FI:egg-console-kit.c	FN:egg_console_kit_init,301
 - Failed to get session for pid 2705: The name org.freedesktop.ConsoleKit was not provided by any .service files
TI:02:11:04	TH:0x1694270	FI:gpm-disks.c	FN:gpm_disks_init,157
 - DBUS error: Could not get owner of name 'org.freedesktop.UDisks': no such name
TI:02:11:04	TH:0x1694270	FI:gpm-button.c	FN:gpm_button_xevent_key,203
 - could not map keysym 1008ffa8 to keycode
TI:02:11:04	TH:0x1694270	FI:gpm-backlight.c	FN:gpm_backlight_brightness_evaluate_and_set,286
 - no dimming hardware
TI:02:11:04	TH:0x1694270	FI:gpm-phone.c	FN:gpm_phone_dbus_connect,258
 - Cannot connect, maybe the daemon is not running: Could not get owner of name 'org.gnome.phone': no such name
 - disk spindown disabled
TI:02:11:04	TH:0x1694270	FI:gpm-main.c	FN:main,256
 - Power Manager is already running in this session.
Traceback:
	mate-power-manager() [0x418f9f]
	mate-power-manager() [0x408639]
	/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf5) [0x7feca759bb45]
	mate-power-manager() [0x408835]
```

There is my problem. Some help will be very welcome.

Thanks in advance for your time.

Mike.

**Comment by monsta** [comment]
We don't support 1.8 releases these days. Please file a bug report in Debian bug tracker.
