### ISSUE TITLE
Lock screen on pm-suspend in MATE

### ISSUE THREAD

**Issue by wechsler42** [mate-desktop/mate-power-manager#184]
Hi there,
I work on Ubuntu MATE 16.04.
I miss or do not find the option that the sceen locks when I suspend my notebook via terminal "pm-suspend". But it does a screen lock while I suspend it via Power Menu >> Suspend. Is there a way to lock the screen  while using "pm-suspend", too?
##

**Comment by monsta** [comment]
This is not a MATE-specific issue. You will find the same behavior in other desktop environments as well.
The solution is to explicitly tell pm-suspend to run some command to lock your screen. You can find some examples [here](https://wiki.archlinux.org/index.php/pm-utils#Locking_the_screen_saver_on_hibernate_or_suspend).
