### ISSUE TITLE
Change brightness via scrolling over tray icon

### ISSUE THREAD

**Issue by Yanpas** [mate-desktop/mate-power-manager#193]
Add support for changing brightness via scrolling over tray icon

**Comment by monsta** [comment]
Just tested - the slider moves when I use mouse scroll, both with slider shown and hidden. Doesn't it work for you?

**Comment by Yanpas** [comment]
I was talking about this ![1](https://2.bp.blogspot.com/-olfny1DtNcY/T70TQjsuDVI/AAAAAAAAI_c/95VBLIrsdZY/s1600/linux-mint-13-mate.png) (battery icon in the tray). It would be handy and consume less space on the panel.

**Comment by monsta** [comment]
Wait... changing brightness by scrolling over battery status icon? :confused:

**Comment by Yanpas** [comment]
Yes)

**Comment by monsta** [comment]
Oh come on... this makes no sense :smile:

Well, I would never thought that scrolling over battery **status** icon would make any changes in the system. I'd be surprised if it did so.
We have a separate brightness applet for that, so let's keep features where they belong.

**Comment by Yanpas** [comment]
OK, I thought it would have been smart feature. Less space is consumed and the same set of features persist)
