### ISSUE TITLE
Migrate mate-power-manager to GtkApplication

### ISSUE THREAD

**Issue by flexiondotorg** [mate-desktop/mate-power-manager#195]
Debian has raised the following bug:

  * **mate-power-manager** - https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=827232

This MATE component needs migrating to GtkApplication:

  * https://developer.gnome.org/gtk3/3.20/gtk-migrating-unique-GtkApplication.html

**Comment by monsta** [comment]
Done for GTK+3 build in https://github.com/mate-desktop/mate-power-manager/commit/69be34ae5e905b2db1f44f84259133d8914f675f.
