### ISSUE TITLE
Provide simple indicator icon like gnome-power-manager does?

### ISSUE THREAD

**Issue by orschiro** [mate-desktop/mate-power-manager#219]
Dear all, 

I would like to fully substitute the gnome-power-manager with its MATE equivalent but I am lacking one feature that causes me to use both of them. 

I am in need of a simple indicator icon that shows me the state of charging and the remaining battery time. 

Would it be possible for mate-power-manager to provide such a basic indicator icon?

Yours,

Robert

gnome-power-manager indicator icon:
![image](https://cloud.githubusercontent.com/assets/170947/26281531/f1e6ba74-3df9-11e7-9137-195e4763956b.png)

**Comment by monsta** [comment]
There is a battery status applet in mate-applets, will it do?

**Comment by orschiro** [comment]
Dear @monsta, 

I think it does!

Maybe my only remark would be to make the icon a bit prettier to fit and integrate better into the MATE desktop. 

But other than that it's fine. :-)

![image](https://user-images.githubusercontent.com/170947/27079731-29b92a94-5039-11e7-8a32-1fc9abf383a2.png)

**Comment by flexiondotorg** [comment]
I've just added `indicator-power` support to Ubuntu MATE 17.10 when an appropriate panel layout is activated via MATE Tweak.

**Comment by orschiro** [comment]
@flexiondotorg thank you! Which are the appropriate panel layouts?

**Comment by flexiondotorg** [comment]
Cupertino, Pantheon, Mutiny, Netbook, Redmond all support the new Indicators and I'll create a new layout called something like "Ubuntu MATE Contemporary" that will support them too.

**Comment by monsta** [comment]
I wonder if the icon from the first screenshot is really from gnome-power-manager. As I see in its source and in Ubuntu package, it has just gnome-power-statistics tool now. The real power management functionality had been moved to gnome-settings-daemon at some point.

**Comment by orschiro** [comment]
Actually no longer relevant. I got used to using indicator-power which received a lot of improvements. Shall I close it?

**Comment by flexiondotorg** [comment]
Support for `indicator-power` is available in Ubuntu MATE when switching to a panel layout other than Traditional. If other distros want to support Indicators, that is their maintainers decision.

**Comment by monsta** [comment]
Ok, I'll close this one. I just wondered which app actually displayed that icon. That is, if it was a tray icon, not a real indicator 🙂
