### ISSUE TITLE
Cannot change brightness through Power Manager or Brightness applet

### ISSUE THREAD

**Issue by yzhxxzxy** [mate-desktop/mate-power-manager#228]
I just upgraded Fedora from 25 to 26, with mate updated from 1.16 to 1.18. Then I cannot change any more the screen brightness through neither the Power Manager nor the Brightness applet.

**Comment by raveit65** [comment]
Why not using the template to file out a report?
Try again...

**Comment by yzhxxzxy** [comment]
Sorry for the informal expression.
I found that running mate-power-manager by hand can solve this problem.

**Comment by yzhxxzxy** [comment]
Sorry for the informal expression.
I found that mate-power-manager does not run when I log in, so running mate-power-manager afterwards can solve this problem.

**Comment by monsta** [comment]
If it's not running, you've probably hit https://github.com/mate-desktop/mate-power-manager/issues/225.

**Comment by yzhxxzxy** [comment]
Thank you @monsta 
I also found that it is just the same problem as in #226
