### ISSUE TITLE
setting screen sleep to never have no effect

### ISSUE THREAD

**Issue by martinbangens** [mate-desktop/mate-power-manager#256]
#### Expected behaviour
that the screen would not sleep

#### Actual behaviour
When I go away for some time about 15-30 min the screen is locked and its a "black screen with light" its no relay turned off 

#### Steps to reproduce the behaviour
I have one user on auto login so the first thing I'll do, is switch to my other user
I have a Swedish locale
from control panel I choose power manager and I set let screen sleep to never

#### MATE general version
1.18.0

#### Package version
1.18.1-1+sonya

#### Linux Distribution
linux mint

**Comment by monsta** [comment]
> the screen is locked and its a "black screen with light" its no relay turned off

This is done by mate-screensaver. It can be changed in the screensaver preferences app.
