### ISSUE TITLE
Power Statistics cannot enable timerstats in Wakeups tab

### ISSUE THREAD

**Issue by flexiondotorg** [mate-desktop/mate-power-manager#305]
#### Expected behaviour

Power Statistics for the Processor should output Wakeup stats in the table.

#### Actual behaviour

The table is empty and Processor wakeups per second says `GDBus.Error:org.freedesktop.UPower.GeneralError: cannot enable timerstats`.

#### Steps to reproduce the behaviour

Open Power Statistics and click Processor.

#### MATE general version

1.22.2 and git master

#### Package version

1.22.2-0ubuntu2

#### Linux Distribution

Ubuntu MATE 19.10

#### Link to downstream report of your Distribution

None as yet.

**Comment by flexiondotorg** [comment]
This issue was **_not_** caused by #303. I tested 1.22 and git master with and without that patch applied.

**Comment by flexiondotorg** [comment]
This issue was **_not_** caused by #303. I tested 1.22 and git master with and without that patch applied.

**Comment by flexiondotorg** [comment]
I have just tested Ubuntu MATE 19.04 with `mate-power-manager` 1.20.3-2 and `upower` 0.99.10-1 and the same issue is present.

**Comment by raveit65** [comment]
I can confirm the issue with released 1.22.2/1/0 and upower-0.99.10/9.

**Comment by rbuj** [comment]
CONFIG_TIMER_STATS was removed from Kernel https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?h=v4.19-rc6&id=20dcfe1b7df4072a3c13bdb7506f7138125d0099

**Comment by raveit65** [comment]
Now i know why gnome-power-statistic doesn't display it any more, only my mouse device.
![Bildschirmfoto zu 2019-09-26 15-28-48](https://user-images.githubusercontent.com/961604/65692168-65c7d780-e072-11e9-81d6-2d3864f2d8e4.png)

**Comment by raveit65** [comment]
So we need that?
https://gitlab.gnome.org/GNOME/gnome-power-manager/commit/8621440250db093f7ec614193126ada1f2eedd9e
With a check for kernel-version?

**Comment by flexiondotorg** [comment]
Probably just drop it. Eventually there will be no kernels that support the feature.

Question is, what UI changes are required? On my desktop and VMs the only thing I see in Power Statistics is the broken time stats.

**Comment by lukefromdc** [comment]
This is confirmed here too, on kernel 5.3.0 and I concur that if it depends on a no longer avaliable kernel feature we should drop it.

 GNOME did manage to find another way of doing this (at least with 2018 kernels) in their gnome-usage application if anyone wants to find a way to bring it back-or fork that whole application and port it to the MATE user interface for that matter.

**Comment by Ph0rkoz** [comment]
Yes, broken in latest linux mint. :(
