### ISSUE TITLE
Power settings not being applied

### ISSUE THREAD

**Issue by crazyBaboon** [mate-desktop/mate-power-manager#379]
I have the following settings:

![Screenshot at 2022-05-15 20-11-29](https://user-images.githubusercontent.com/19549703/168489906-f0e9c62b-2824-41ce-abc6-6c68ad0065ef.png)

but  when I don't touch my desktop for 5 min or so, it goes to sleep mode, so I have to type the password again when i get back to it.

I am using Manjaro-Mate.

**Comment by lukefromdc** [comment]
Is mate-power-manager running when this happens?

**Comment by lukefromdc** [comment]
Also, try adding the inhibit applet to the panel, it can be used to overrride this sort of behavior.

**Comment by crazyBaboon** [comment]
I had to format the PC. When I installed manjaro-mate again, this problem was gone. Closing this issue. Thanks anyway!
