### ISSUE TITLE
meson.build files are not in released 1.28 tarball generated with distcheck

### ISSUE THREAD

**Issue by raveit65** [mate-desktop/mate-power-manager#396]
#### Expected behaviour
Working releasing with travis-ci

#### Actual behaviour
Meson.build files are missing

#### Steps to reproduce the behaviour

Check released tarball https://github.com/mate-desktop/mate-power-manager/releases/tag/v1.28.0
#### MATE general version

1.28
#### Package version
1.28.0

**Comment by raveit65** [comment]
@mate-desktop/core-team

**Comment by lukefromdc** [comment]
https://github.com/mate-desktop/mate-power-manager/pull/397
works fine.

**Comment by raveit65** [comment]
https://github.com/mate-desktop/mate-power-manager/commit/c406c230d131702c1f2bc28ea386b4e3fb774936 is merged
