### ISSUE TITLE
right/left mouse clicks are reversed at brightness applet slider

### ISSUE THREAD

**Issue by raveit65** [mate-desktop/mate-power-manager#62]
original report at fedora bugzilla.
https://bugzilla.redhat.com/show_bug.cgi?id=965633

Description of problem:
When trying to change brightness from mate-panel, clicking on any level or '+'/'-' buttons will just collapse the menu without setting the brightness level.

Version-Release number of selected component (if applicable):
mate-applets-1.6.1-1.fc19.x86_64

How reproducible:
Always

Steps to Reproduce:
1. Right click on panel -> Add to Panel
2. Brightness Applet -> Add
3. Click on Brightness -> try to change brightness level

Actual results:
Brightness does not change

Expected results:
Brightness is changed

Additional info:
Scrolling up&down on the brightness icon -> adjusting brightness takes a lot of time (not immediate reaction)

**Comment by raveit65** [comment]
re-opend because it is broken with gtk3

**Comment by rezso** [comment]
I can compile it with this patch:
https://gist.github.com/rezso/9db8c4aa202790607f4b

**Comment by raveit65** [comment]
@rezso 
this is for gtk2 build ?

**Comment by rezso** [comment]
@raveit65 
No. This is for gtk2 and gtk3 build.
gtk_widget_set_can_focus is useable since gtk 2.18, mate-power-manager requires gtk2 2.24 or gtk3.

**Comment by raveit65** [comment]
thx for clarifications, i did ask because i prepared a more extended patch yet :) 
https://dl.dropboxusercontent.com/u/49862637/Mate-desktop/Bugs/mate-power-manager_fix-brightness-applet-new.patch
.......more than 1 way to rome......

**Comment by rezso** [comment]
Your patch made for mouse clicks, mine is simple build fix for https://github.com/mate-desktop/mate-power-manager/issues/62#issuecomment-36772410.

**Comment by raveit65** [comment]
I now what my patch was made for, but you did't say for what your patch is good for.....
Header is not about using --strict or not.

**Comment by raveit65** [comment]
hmm, with your patch the brightness slider isn't selectable again with gtk2 build.
